name: Deploy to Minikube

on:
  push:
    branches:
      - develop 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push my-app:${{ github.sha }}

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yml  # Asegúrate de que tu archivo de despliegue esté en la carpeta correcta
